In [1]:
from google.colab import files
files.upload()

Saving salary_prediction_data.csv to salary_prediction_data.csv

{'salary_prediction_data.csv': b'Education,Experience,Location,Job_Title,Age,Gender,Salary\nHigh School,8,Urban,Manager,63,Male,84620.05366451902\nPhD,11,Suburban,Director,59,Male,142591.2558943053\nBachelor,28,Suburban,Manager,61,Female,97800.25540414132\nHigh School,29,Rural,Director,45,Male,96834.67128150171\nPhD,25,Urban,Analyst,26,Female,132157.78617465615\nPhD,19,Rural,Director,27,Female,156312.9362084037\nPhD,4,Rural,Director,60,Female,130567.64945544896\nPhD,13,Suburban,Director,49,Female,148707.74075900653\nBachelor,20,Urban,Engineer,25,Female,95945.27542859329\nPhD,14,Urban,Analyst,58,Female,133339.3896823029\nBachelor,23,Rural,Manager,23,Female,101164.09236529446\nMaster,1,Urban,Director,27,Female,124251.98714687066\nHigh School,11,Urban,Manager,63,Male,55066.114352582896\nPhD,4,Rural,Manager,43,Male,124972.50876977787\nMaster,7,Suburban,Director,44,Female,126139.13670110232\nHigh School,28,Suburban,Engineer,49,Male,81007.19945085408\nHigh School,4,Suburban,Analyst,37,Male,60693.924713925415\nHigh School,26,Rural,Director,63,Male,103386.0702899282\nMaster,7,Urban,Director,53,Female,140042.13891849504\nBachelor,20,Rural,Analyst,34,Male,86048.11608072282\nMaster,3,Rural,Engineer,62,Female,73861.99295330019\nPhD,19,Suburban,Analyst,62,Male,106145.00551210355\nPhD,19,Urban,Director,36,Female,142981.59047925484\nMaster,7,Suburban,Analyst,21,Female,96620.92938815863\nHigh School,21,Urban,Manager,62,Female,89426.94711719434\nBachelor,12,Urban,Manager,20,Male,104762.39852019974\nBachelor,23,Suburban,Manager,35,Female,101747.54077442826\nBachelor,1,Suburban,Engineer,36,Male,68635.08828494251\nBachelor,5,Rural,Manager,28,Male,90550.47942410434\nHigh School,14,Urban,Analyst,61,Female,75559.24411372501\nBachelor,10,Urban,Engineer,40,Female,87433.49864519518\nHigh School,3,Urban,Analyst,63,Female,57615.23341761047\nPhD,2,Urban,Engineer,45,Male,126043.14343328991\nHigh School,13,Urban,Analyst,20,Male,73043.43575162995\nPhD,16,Rural,Director,59,Male,134560.1930040126\nBachelor,23,Urban,Engineer,22,Female,95804.2614408205\nMaster,2,Rural,Director,26,Female,99694.53954354613\nPhD,24,Suburban,Director,23,Female,153930.9338516317\nPhD,13,Rural,Director,50,Male,151123.33589341832\nHigh School,6,Rural,Director,33,Female,81462.71866943766\nMaster,7,Rural,Director,40,Male,106019.02039637441\nPhD,2,Suburban,Director,31,Female,142122.66726825983\nHigh School,11,Urban,Analyst,31,Male,66858.43105342452\nBachelor,7,Rural,Manager,25,Female,82060.7329291408\nPhD,7,Suburban,Engineer,36,Female,107935.40344896368\nBachelor,7,Rural,Analyst,33,Male,70251.76628382233\nPhD,7,Rural,Analyst,28,Female,118799.44006115955\nPhD,12,Suburban,Analyst,47,Female,100369.02351603874\nMaster,19,Rural,Analyst,26,Male,100038.7680224855\nPhD,22,Rural,Manager,64,Male,164542.83698804962\nHigh School,19,Urban,Manager,62,Male,95726.36718568094\nBachelor,19,Suburban,Engineer,24,Male,96598.32495003476\nBachelor,20,Rural,Engineer,60,Female,82628.14830429087\nBachelor,3,Suburban,Analyst,61,Female,66216.7016212603\nPhD,13,Suburban,Engineer,35,Female,127167.11604300037\nHigh School,10,Urban,Director,20,Female,106028.63629377136\nPhD,20,Urban,Analyst,59,Male,139655.8919089493\nMaster,9,Urban,Engineer,57,Male,100278.41602229177\nHigh School,6,Rural,Engineer,26,Female,67767.86962383863\nPhD,21,Rural,Director,49,Male,148074.0579284191\nPhD,22,Rural,Analyst,45,Female,143973.4648101395\nMaster,12,Rural,Manager,32,Female,106333.96975362297\nPhD,2,Rural,Analyst,20,Female,96967.34243096111\nMaster,12,Rural,Manager,48,Female,113746.2957781357\nPhD,16,Suburban,Engineer,27,Female,140823.26983800298\nHigh School,13,Suburban,Manager,21,Female,88374.4479673091\nMaster,16,Urban,Analyst,64,Female,112591.91766668811\nHigh School,13,Rural,Engineer,27,Male,53119.03312031389\nHigh School,22,Suburban,Manager,60,Female,81946.59278102114\nHigh School,25,Urban,Manager,46,Female,74817.18131645783\nBachelor,19,Urban,Analyst,60,Male,84868.7846243118\nBachelor,26,Urban,Engineer,42,Male,104215.43185102737\nMaster,14,Urban,Engineer,34,Male,117890.0214065348\nHigh School,29,Suburban,Manager,51,Male,90605.4567853522\nHigh School,13,Suburban,Manager,41,Female,77430.20945022261\nBachelor,10,Suburban,Manager,27,Male,91038.14555250182\nPhD,22,Urban,Director,56,Male,169510.2530418977\nHigh School,7,Urban,Engineer,36,Male,58008.87061573461\nBachelor,5,Rural,Manager,26,Female,93375.47914146326\nMaster,17,Rural,Manager,62,Female,136608.8081251391\nMaster,9,Urban,Engineer,40,Female,113727.8965602193\nPhD,27,Suburban,Director,58,Male,156729.08389775958\nHigh School,6,Urban,Engineer,24,Female,60637.29855913215\nBachelor,16,Rural,Director,36,Female,118098.37222184098\nBachelor,6,Rural,Analyst,54,Male,59734.10574128003\nPhD,6,Suburban,Engineer,34,Male,111461.95579727436\nBachelor,28,Urban,Engineer,59,Male,96355.51546129535\nBachelor,18,Rural,Analyst,35,Male,70214.86159479314\nPhD,1,Suburban,Engineer,44,Male,105551.83680620143\nMaster,17,Rural,Analyst,34,Male,109899.04941785493\nPhD,17,Suburban,Director,30,Male,163022.82564588025\nPhD,1,Rural,Engineer,24,Male,104029.26927639818\nMaster,11,Rural,Analyst,40,Female,98073.3404604569\nMaster,13,Urban,Manager,61,Female,130591.56675108234\nPhD,1,Suburban,Director,60,Male,137005.64203097162\nHigh School,27,Suburban,Director,31,Male,92450.57242382762\nMaster,8,Rural,Manager,49,Female,93295.98264861919\nPhD,23,Urban,Manager,23,Male,163104.2755312551\nBachelor,20,Rural,Analyst,64,Male,89961.7941228838\nHigh School,6,Rural,Manager,46,Male,71769.55893398654\nBachelor,5,Rural,Engineer,47,Male,63923.5309909897\nMaster,20,Suburban,Analyst,22,Female,112349.77192889052\nHigh School,5,Urban,Director,22,Male,91289.99587456821\nPhD,6,Rural,Engineer,43,Female,119140.33843647146\nHigh School,29,Rural,Engineer,48,Male,71549.7678319231\nMaster,13,Rural,Director,38,Female,133122.60510065337\nHigh School,27,Suburban,Engineer,21,Female,66723.68051821226\nPhD,18,Rural,Director,24,Male,157287.4192480694\nPhD,20,Suburban,Director,56,Female,165810.55944087074\nHigh School,13,Suburban,Director,37,Female,103723.30317535225\nPhD,7,Suburban,Director,44,Female,138575.07809749557\nHigh School,8,Suburban,Analyst,45,Female,48005.699834384795\nHigh School,21,Suburban,Engineer,63,Female,83938.8036230838\nHigh School,17,Urban,Manager,32,Male,80007.84720913025\nHigh School,1,Suburban,Analyst,54,Male,51439.95511443989\nMaster,24,Suburban,Manager,41,Female,125825.37782839929\nPhD,16,Rural,Analyst,29,Female,111979.28028586916\nHigh School,11,Urban,Engineer,56,Female,74209.99466184892\nPhD,29,Urban,Director,63,Male,155079.84083441965\nMaster,4,Rural,Manager,61,Male,109922.0568164404\nPhD,4,Suburban,Analyst,26,Male,104330.68911543266\nPhD,17,Urban,Engineer,37,Female,119682.68653532074\nBachelor,17,Suburban,Engineer,51,Female,91498.92541209707\nBachelor,10,Rural,Analyst,64,Male,79316.33852811223\nBachelor,21,Urban,Director,26,Male,126769.34597053225\nHigh School,21,Suburban,Analyst,36,Female,79183.53730827161\nBachelor,6,Urban,Analyst,50,Male,57463.59600309587\nBachelor,25,Urban,Analyst,48,Male,89948.55569043328\nBachelor,25,Suburban,Director,31,Male,121066.52294503032\nPhD,17,Suburban,Manager,52,Female,157190.03279936145\nHigh School,18,Urban,Analyst,58,Male,80837.44493674728\nPhD,22,Rural,Engineer,45,Male,151013.40051848112\nBachelor,26,Urban,Manager,58,Female,110750.60577086001\nMaster,10,Rural,Engineer,49,Male,102744.16995282008\nHigh School,13,Urban,Engineer,22,Female,62000.29192430693\nBachelor,16,Suburban,Analyst,39,Female,81956.47780376\nMaster,7,Rural,Manager,32,Female,99647.04281717027\nHigh School,15,Rural,Analyst,38,Female,53660.11340683279\nMaster,2,Urban,Engineer,20,Male,98065.50878814337\nHigh School,5,Urban,Analyst,61,Male,60027.17539890681\nBachelor,17,Rural,Director,42,Male,107222.12664516484\nPhD,5,Suburban,Director,37,Female,145434.53439582724\nMaster,8,Rural,Analyst,62,Male,94399.8846738686\nMaster,24,Rural,Analyst,24,Female,105559.54371150375\nBachelor,28,Suburban,Analyst,24,Male,92774.21458468054\nHigh School,15,Suburban,Analyst,38,Female,61928.68279841316\nPhD,8,Urban,Analyst,25,Female,118509.62858553034\nBachelor,23,Urban,Director,34,Female,127909.7105518198\nBachelor,3,Urban,Manager,30,Male,101655.25190671263\nPhD,23,Suburban,Analyst,49,Female,145740.44537947085\nHigh School,17,Rural,Manager,39,Female,69022.97240059583\nMaster,28,Suburban,Analyst,54,Male,122693.7222533875\nMaster,16,Urban,Manager,23,Female,112053.20358407324\nPhD,16,Rural,Director,28,Female,149731.74718252578\nMaster,19,Urban,Engineer,46,Male,129826.72282091064\nPhD,12,Rural,Manager,38,Female,130504.10498333005\nPhD,24,Suburban,Director,24,Male,169726.36047258874\nPhD,15,Urban,Manager,27,Female,133614.32129684524\nMaster,8,Suburban,Director,62,Male,114113.54716908363\nBachelor,27,Suburban,Engineer,49,Female,100641.90157356314\nMaster,3,Suburban,Director,55,Male,128222.10354585825\nMaster,23,Rural,Analyst,35,Female,103825.70543658012\nPhD,18,Suburban,Analyst,23,Female,123464.46899091225\nMaster,4,Suburban,Manager,23,Female,99083.71641621979\nPhD,8,Rural,Analyst,26,Male,115028.81044442621\nPhD,14,Suburban,Analyst,22,Female,136466.95140894435\nMaster,28,Suburban,Engineer,57,Male,130006.80109093692\nMaster,17,Suburban,Analyst,44,Male,113966.50654336264\nPhD,6,Rural,Analyst,55,Male,108930.25525076337\nHigh School,5,Rural,Manager,23,Female,59366.90640736085\nBachelor,22,Urban,Analyst,27,Female,103772.45916416371\nMaster,14,Suburban,Analyst,47,Female,103680.88924365859\nPhD,6,Rural,Director,22,Male,134263.9176428062\nMaster,20,Suburban,Director,27,Female,143982.40622403615\nBachelor,12,Rural,Manager,30,Male,90022.1254832727\nMaster,9,Rural,Manager,25,Male,100622.23740614793\nBachelor,1,Rural,Manager,60,Female,90091.88495330967\nHigh School,18,Urban,Analyst,42,Male,73807.19890433867\nMaster,6,Suburban,Analyst,63,Male,85629.70656151309\nMaster,29,Rural,Analyst,21,Male,102870.94105128384\nPhD,5,Suburban,Analyst,26,Female,115954.11875826867\nHigh School,2,Rural,Analyst,48,Male,70374.09661478276\nPhD,6,Suburban,Analyst,25,Female,112071.79396453791\nMaster,17,Suburban,Director,60,Male,128637.26140914421\nPhD,7,Rural,Manager,30,Male,142237.71197617054\nHigh School,25,Suburban,Manager,27,Female,89427.18800209484\nHigh School,9,Urban,Analyst,49,Male,49515.33136752012\nMaster,23,Urban,Engineer,56,Male,107272.03547451827\nHigh School,20,Suburban,Director,38,Female,107266.63973787481\nMaster,5,Suburban,Manager,22,Female,116663.54542250189\nPhD,21,Rural,Director,61,Male,159261.25708431192\nMaster,11,Rural,Analyst,49,Male,95422.43441621287\nMaster,11,Suburban,Director,52,Male,118732.87974017202\nPhD,28,Suburban,Manager,45,Male,150828.36884275833\nHigh School,4,Suburban,Director,56,Male,80360.31217374376\nHigh School,23,Suburban,Director,39,Male,89616.88844301298\nHigh School,29,Urban,Engineer,52,Female,94614.49909551127\nBachelor,6,Suburban,Director,47,Male,88404.03831200278\nMaster,27,Rural,Manager,46,Female,123672.41235424776\nHigh School,10,Urban,Manager,48,Female,77959.92127523497\nBachelor,9,Suburban,Manager,43,Male,87089.80186824632\nMaster,29,Rural,Manager,38,Female,106944.94644980178\nPhD,18,Urban,Analyst,25,Male,137478.69664111253\nMaster,20,Suburban,Engineer,21,Female,107442.49239559734\nMaster,9,Suburban,Analyst,41,Male,112257.07959324372\nPhD,28,Suburban,Manager,54,Male,149580.17722315947\nBachelor,11,Suburban,Director,21,Female,100586.4041156878\nHigh School,2,Urban,Manager,49,Female,72915.21946778877\nHigh School,15,Rural,Manager,54,Male,85534.39748630449\nHigh School,6,Suburban,Engineer,34,Female,55365.9233688183\nPhD,25,Urban,Engineer,62,Male,155147.37694829778\nPhD,17,Urban,Director,50,Male,171403.03641017622\nHigh School,4,Rural,Analyst,29,Female,58903.22810655946\nMaster,8,Urban,Manager,47,Female,134264.31490992257\nMaster,29,Urban,Engineer,27,Male,141926.4602101247\nHigh School,2,Rural,Director,32,Male,87148.82293893005\nHigh School,24,Urban,Manager,49,Male,110043.26319415642\nPhD,9,Urban,Analyst,56,Male,126080.69529629964\nHigh School,1,Rural,Analyst,58,Male,41707.761004278014\nBachelor,24,Urban,Engineer,48,Male,81377.56364756194\nMaster,6,Rural,Analyst,41,Male,77772.66880478204\nHigh School,16,Suburban,Director,43,Female,86517.17200841205\nHigh School,27,Suburban,Engineer,57,Male,78182.64912759434\nPhD,26,Suburban,Manager,40,Male,149472.05536597915\nBachelor,26,Suburban,Engineer,33,Male,90992.3950975125\nPhD,7,Urban,Director,60,Male,131042.22388558686\nHigh School,25,Suburban,Director,61,Female,98697.76833533274\nMaster,24,Rural,Analyst,21,Male,107105.8207118821\nBachelor,16,Rural,Manager,28,Female,87924.45958450134\nBachelor,6,Rural,Director,59,Female,88578.47838349616\nBachelor,10,Rural,Analyst,64,Female,65598.43408127593\nPhD,18,Suburban,Manager,29,Female,139034.76260983682\nHigh School,17,Rural,Manager,37,Female,68436.97173004749\nHigh School,17,Suburban,Director,45,Female,104598.75331517015\nHigh School,12,Rural,Manager,43,Female,74409.96732045121\nBachelor,15,Rural,Manager,60,Female,85276.82081973483\nBachelor,6,Suburban,Analyst,30,Female,73195.52218532546\nMaster,23,Suburban,Engineer,46,Male,106197.1439364881\nBachelor,20,Urban,Manager,33,Male,120121.68295174788\nHigh School,16,Urban,Analyst,51,Female,84841.8672458082\nHigh School,23,Urban,Analyst,41,Female,90520.01982753031\nBachelor,14,Rural,Analyst,53,Female,67553.07368757403\nMaster,12,Rural,Director,21,Male,121087.32980273824\nBachelor,12,Rural,Director,52,Male,97984.29324487085\nBachelor,2,Urban,Engineer,63,Female,87620.13105914182\nPhD,8,Urban,Director,26,Female,137920.90196716101\nBachelor,24,Urban,Analyst,54,Male,92241.08305998983\nHigh School,27,Rural,Analyst,50,Female,67867.82971648192\nHigh School,17,Suburban,Engineer,46,Male,73532.88469132425\nHigh School,8,Urban,Analyst,58,Male,69941.28708137886\nPhD,16,Suburban,Director,56,Female,147712.72307263393\nPhD,23,Rural,Analyst,37,Male,134639.6507552622\nBachelor,1,Urban,Engineer,32,Male,89220.76356797137\nMaster,5,Rural,Engineer,59,Male,92867.8476312818\nBachelor,19,Suburban,Engineer,45,Male,81543.41867134403\nPhD,24,Rural,Manager,20,Female,132288.0966456586\nBachelor,22,Rural,Director,58,Male,117917.26975151568\nPhD,3,Urban,Engineer,50,Female,118237.75563685331\nHigh School,9,Suburban,Manager,61,Male,56873.70677317545\nHigh School,11,Urban,Director,56,Female,97129.52368183\nPhD,6,Rural,Manager,58,Male,127295.54520546219\nBachelor,7,Rural,Director,48,Male,82940.32918857371\nMaster,7,Suburban,Director,62,Male,133794.19981202646\nHigh School,5,Rural,Director,43,Female,83366.3598715775\nMaster,2,Urban,Engineer,35,Female,103387.4525129018\nPhD,22,Suburban,Director,58,Male,144256.80632265584\nPhD,28,Rural,Manager,58,Female,133976.69467114715\nMaster,5,Urban,Analyst,42,Male,96929.31513158564\nPhD,6,Urban,Analyst,27,Male,103860.8461044971\nBachelor,6,Suburban,Director,57,Male,105050.80273184486\nBachelor,7,Rural,Engineer,22,Male,62891.76686619663\nBachelor,4,Urban,Director,33,Female,105649.12729254698\nPhD,25,Suburban,Manager,40,Male,147118.68547273273\nMaster,18,Urban,Analyst,49,Female,120117.85268097043\nHigh School,16,Rural,Manager,52,Male,66620.52404738512\nHigh School,21,Urban,Manager,39,Male,93737.29449524725\nBachelor,19,Rural,Analyst,64,Female,70051.59807165357\nHigh School,10,Urban,Engineer,64,Female,77955.49551769407\nPhD,24,Rural,Manager,42,Female,142850.38233722505\nMaster,5,Urban,Analyst,42,Male,104958.5066896543\nPhD,18,Urban,Engineer,64,Male,124794.74653171968\nPhD,25,Suburban,Manager,57,Male,154990.84275671767\nMaster,3,Rural,Manager,54,Female,106062.03396303709\nHigh School,20,Urban,Manager,58,Male,93636.97892713363\nMaster,4,Suburban,Manager,41,Female,112126.33963013986\nPhD,14,Urban,Director,48,Male,152065.3611720965\nMaster,12,Suburban,Engineer,54,Female,119412.99220315991\nMaster,14,Urban,Manager,21,Male,122441.02014234297\nBachelor,5,Suburban,Analyst,37,Male,67608.30799609171\nBachelor,18,Rural,Director,54,Female,107412.73806631062\nPhD,27,Urban,Analyst,63,Male,132494.82054555468\nPhD,7,Rural,Analyst,33,Male,107360.03576669157\nHigh School,16,Rural,Engineer,37,Female,64227.533838106014\nPhD,3,Suburban,Analyst,51,Male,109204.4587935414\nHigh School,22,Rural,Director,41,Female,93993.97072805486\nHigh School,21,Suburban,Manager,54,Female,105457.61391306327\nMaster,11,Suburban,Manager,21,Male,121709.4983984612\nMaster,27,Suburban,Analyst,25,Male,127723.00647288091\nPhD,26,Suburban,Engineer,58,Female,135962.90562631763\nBachelor,18,Suburban,Engineer,51,Female,87129.83711494852\nBachelor,6,Urban,Manager,48,Male,92218.2195310701\nHigh School,26,Urban,Manager,58,Male,104528.89097268877\nPhD,21,Rural,Analyst,24,Male,104518.81521769102\nHigh School,22,Urban,Engineer,57,Female,71668.35224708632\nMaster,24,Suburban,Analyst,27,Female,115023.3584683422\nPhD,5,Suburban,Manager,23,Female,127759.07632937071\nPhD,5,Urban,Manager,41,Male,154677.29682143047\nBachelor,16,Rural,Analyst,41,Female,85476.83215742656\nPhD,3,Rural,Engineer,46,Male,106378.0855646952\nBachelor,12,Urban,Manager,22,Male,86223.92931460653\nPhD,3,Suburban,Manager,48,Male,124594.39965062137\nMaster,2,Suburban,Engineer,52,Male,83967.79917321586\nHigh School,15,Rural,Manager,57,Female,79667.50650418435\nBachelor,20,Urban,Engineer,53,Male,101611.06322241678\nBachelor,17,Suburban,Engineer,55,Female,95200.31932092732\nPhD,12,Rural,Manager,52,Female,152791.76664795037\nPhD,2,Rural,Analyst,59,Male,97925.34018579702\nPhD,26,Urban,Manager,37,Female,154075.95792204092\nBachelor,2,Rural,Manager,29,Female,69874.84255511091\nBachelor,14,Suburban,Manager,55,Male,98194.01483849874\nBachelor,7,Rural,Director,64,Female,112932.73615950027\nPhD,26,Rural,Manager,42,Male,151687.22399120472\nPhD,25,Rural,Analyst,25,Male,128855.12954410799\nMaster,14,Urban,Analyst,42,Male,111516.30248819891\nMaster,7,Suburban,Analyst,29,Female,84891.4436205641\nMaster,20,Rural,Engineer,21,Male,106062.66288305611\nHigh School,17,Urban,Director,63,Female,97852.52574570387\nPhD,24,Rural,Director,25,Female,154994.21986708543\nPhD,27,Suburban,Analyst,62,Female,121693.83755601384\nBachelor,4,Rural,Director,24,Female,97276.23179234781\nMaster,27,Urban,Engineer,27,Male,129791.9649251421\nPhD,15,Rural,Manager,39,Male,131229.4879372722\nBachelor,27,Rural,Analyst,58,Female,92041.749990825\nPhD,3,Rural,Director,33,Female,118165.08446631998\nPhD,6,Urban,Analyst,31,Male,106202.04384675651\nBachelor,26,Rural,Analyst,43,Female,92346.87262338237\nBachelor,8,Rural,Analyst,58,Male,66322.76809083836\nBachelor,16,Urban,Analyst,31,Male,90884.44479775698\nHigh School,15,Urban,Manager,60,Female,93394.90672317604\nMaster,4,Suburban,Analyst,51,Female,92260.70069694844\nMaster,21,Urban,Director,23,Male,112893.31945170803\nHigh School,8,Rural,Director,22,Male,76493.46361979107\nBachelor,23,Rural,Engineer,27,Female,88189.55978005964\nBachelor,8,Urban,Engineer,22,Male,85653.0564567708\nHigh School,20,Suburban,Director,45,Female,103997.30812571553\nPhD,7,Urban,Analyst,25,Male,106214.69814058887\nHigh School,26,Suburban,Director,36,Male,103439.56623907984\nHigh School,20,Urban,Engineer,28,Female,95703.03911911232\nPhD,24,Suburban,Analyst,37,Male,127740.56885031542\nMaster,18,Suburban,Director,48,Female,137723.27886185737\nBachelor,12,Rural,Manager,34,Male,101663.05778970802\nMaster,4,Suburban,Director,26,Female,121102.31439102095\nBachelor,14,Rural,Engineer,33,Female,77149.03019668574\nMaster,27,Urban,Director,48,Female,139904.78989292\nHigh School,24,Urban,Analyst,23,Female,86438.00153765982\nMaster,25,Urban,Director,64,Male,150921.49090781735\nHigh School,28,Urban,Engineer,58,Male,80135.31584928774\nBachelor,29,Urban,Director,24,Male,117235.26845638917\nBachelor,25,Rural,Analyst,20,Male,77191.93285851003\nBachelor,5,Urban,Director,31,Male,121616.51861184771\nHigh School,22,Suburban,Engineer,58,Male,76320.54879609501\nPhD,20,Rural,Manager,26,Male,163602.28585653414\nHigh School,23,Suburban,Director,40,Male,103555.45603070543\nPhD,26,Rural,Director,26,Male,160395.223228338\nHigh School,7,Suburban,Engineer,36,Male,65062.72488305184\nHigh School,12,Rural,Engineer,20,Male,71991.49850197365\nHigh School,15,Urban

In [2]:
import pandas as pd
df = pd.read_csv('salary_prediction_data.csv')

In [4]:
df

       Education  Experience  Location Job_Title  Age  Gender         Salary
0    High School           8     Urban   Manager   63    Male   84620.053665
1            PhD          11  Suburban  Director   59    Male  142591.255894
2       Bachelor          28  Suburban   Manager   61  Female   97800.255404
3    High School          29     Rural  Director   45    Male   96834.671282
4            PhD          25     Urban   Analyst   26  Female  132157.786175
..           ...         ...       ...       ...  ...     ...            ...
995  High School           8  Suburban   Analyst   25  Female   64683.389864
996  High School          24     Urban  Engineer   30  Female   74468.205020
997       Master          18     Rural   Analyst   44    Male   98207.026024
998     Bachelor          27  Suburban  Director   31  Female  108544.922720
999  High School          25     Urban  Director   41  Female   71077.000066

[1000 rows x 7 columns]

In [5]:
df.head()

     Education  Experience  Location Job_Title  Age  Gender         Salary
0  High School           8     Urban   Manager   63    Male   84620.053665
1          PhD          11  Suburban  Director   59    Male  142591.255894
2     Bachelor          28  Suburban   Manager   61  Female   97800.255404
3  High School          29     Rural  Director   45    Male   96834.671282
4          PhD          25     Urban   Analyst   26  Female  132157.786175

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Education   1000 non-null   object
 1   Experience  1000 non-null   int64
 2   Location    1000 non-null   object
 3   Job_Title   1000 non-null   object
 4   Age         1000 non-null   int64
 5   Gender      1000 non-null   object
 6   Salary      1000 non-null   float64
dtypes: float64(1), int64(2), object(4)
memory usage: 54.8+ KB

In [7]:
df.isnull().sum()

Education     0
Experience    0
Location      0
Job_Title     0
Age           0
Gender        0
Salary        0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Education   1000 non-null   object
 1   Experience  1000 non-null   int64
 2   Location    1000 non-null   object
 3   Job_Title   1000 non-null   object
 4   Age         1000 non-null   int64
 5   Gender      1000 non-null   object
 6   Salary      1000 non-null   float64
dtypes: float64(1), int64(2), object(4)
memory usage: 54.8+ KB

In [9]:
df.describe()

        Experience          Age         Salary
count  1000.000000  1000.000000    1000.000000
mean     14.771000    42.377000  105558.404239
std       8.341111    13.609412   28256.972075
min       1.000000    20.000000   33510.510669
25%       7.000000    30.000000   85032.141517
50%      15.000000    43.000000  104314.518315
75%      22.000000    55.000000  126804.047524
max      29.000000    64.000000  193016.602150

In [10]:
df

       Education  Experience  Location Job_Title  Age  Gender         Salary
0    High School           8     Urban   Manager   63    Male   84620.053665
1            PhD          11  Suburban  Director   59    Male  142591.255894
2       Bachelor          28  Suburban   Manager   61  Female   97800.255404
3    High School          29     Rural  Director   45    Male   96834.671282
4            PhD          25     Urban   Analyst   26  Female  132157.786175
..           ...         ...       ...       ...  ...     ...            ...
995  High School           8  Suburban   Analyst   25  Female   64683.389864
996  High School          24     Urban  Engineer   30  Female   74468.205020
997       Master          18     Rural   Analyst   44    Male   98207.026024
998     Bachelor          27  Suburban  Director   31  Female  108544.922720
999  High School          25     Urban  Director   41  Female   71077.000066

[1000 rows x 7 columns]

In [11]:
edu_map = {'Bachelors': 1, 'Masters': 2, 'PhD': 3}
df['Education'] = df['Education'].map(edu_map)

In [12]:
df

     Education  Experience  Location Job_Title  Age  Gender         Salary
0          NaN           8     Urban   Manager   63    Male   84620.053665
1          3.0          11  Suburban  Director   59    Male  142591.255894
2          NaN          28  Suburban   Manager   61  Female   97800.255404
3          NaN          29     Rural  Director   45    Male   96834.671282
4          3.0          25     Urban   Analyst   26  Female  132157.786175
..         ...         ...       ...       ...  ...     ...            ...
995        NaN           8  Suburban   Analyst   25  Female   64683.389864
996        NaN          24     Urban  Engineer   30  Female   74468.205020
997        NaN          18     Rural   Analyst   44    Male   98207.026024
998        NaN          27  Suburban  Director   31  Female  108544.922720
999        NaN          25     Urban  Director   41  Female   71077.000066

[1000 rows x 7 columns]

In [14]:
df['Education'].unique()

array([nan,  3.])

In [15]:
df['Education'].value_counts()

Education
3.0    251
Name: count, dtype: int64

In [16]:
df = pd.read_csv('salary_prediction_data.csv')

In [17]:
df

       Education  Experience  Location Job_Title  Age  Gender         Salary
0    High School           8     Urban   Manager   63    Male   84620.053665
1            PhD          11  Suburban  Director   59    Male  142591.255894
2       Bachelor          28  Suburban   Manager   61  Female   97800.255404
3    High School          29     Rural  Director   45    Male   96834.671282
4            PhD          25     Urban   Analyst   26  Female  132157.786175
..           ...         ...       ...       ...  ...     ...            ...
995  High School           8  Suburban   Analyst   25  Female   64683.389864
996  High School          24     Urban  Engineer   30  Female   74468.205020
997       Master          18     Rural   Analyst   44    Male   98207.026024
998     Bachelor          27  Suburban  Director   31  Female  108544.922720
999  High School          25     Urban  Director   41  Female   71077.000066

[1000 rows x 7 columns]

In [18]:
df['Education'].value_counts()

Education
High School    255
Bachelor       253
PhD            251
Master         241
Name: count, dtype: int64

In [21]:
edu_map = {
    'High School': 0,
    'Bachelor': 1,
    'Master': 2,
    'PhD': 3
}

df['Education'] = df['Education'].map(edu_map)

In [22]:
df

     Education  Experience  Location Job_Title  Age  Gender         Salary
0          NaN           8     Urban   Manager   63    Male   84620.053665
1          NaN          11  Suburban  Director   59    Male  142591.255894
2          NaN          28  Suburban   Manager   61  Female   97800.255404
3          NaN          29     Rural  Director   45    Male   96834.671282
4          NaN          25     Urban   Analyst   26  Female  132157.786175
..         ...         ...       ...       ...  ...     ...            ...
995        NaN           8  Suburban   Analyst   25  Female   64683.389864
996        NaN          24     Urban  Engineer   30  Female   74468.205020
997        NaN          18     Rural   Analyst   44    Male   98207.026024
998        NaN          27  Suburban  Director   31  Female  108544.922720
999        NaN          25     Urban  Director   41  Female   71077.000066

[1000 rows x 7 columns]

In [23]:
df = pd.read_csv('salary_prediction_data.csv')
df['Education'].unique()  # to confirm it's restored

array(['High School', 'PhD', 'Bachelor', 'Master'], dtype=object)

In [24]:
df

       Education  Experience  Location Job_Title  Age  Gender         Salary
0    High School           8     Urban   Manager   63    Male   84620.053665
1            PhD          11  Suburban  Director   59    Male  142591.255894
2       Bachelor          28  Suburban   Manager   61  Female   97800.255404
3    High School          29     Rural  Director   45    Male   96834.671282
4            PhD          25     Urban   Analyst   26  Female  132157.786175
..           ...         ...       ...       ...  ...     ...            ...
995  High School           8  Suburban   Analyst   25  Female   64683.389864
996  High School          24     Urban  Engineer   30  Female   74468.205020
997       Master          18     Rural   Analyst   44    Male   98207.026024
998     Bachelor          27  Suburban  Director   31  Female  108544.922720
999  High School          25     Urban  Director   41  Female   71077.000066

[1000 rows x 7 columns]

In [25]:
edu_map = {
    'High School': 0,
    'Bachelor': 1,
    'Master': 2,
    'PhD': 3
}

df['Education'] = df['Education'].map(edu_map)

In [26]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Education   1000 non-null   int64
 1   Experience  1000 non-null   int64
 2   Location    1000 non-null   object
 3   Job_Title   1000 non-null   object
 4   Age         1000 non-null   int64
 5   Gender      1000 non-null   object
 6   Salary      1000 non-null   float64
dtypes: float64(1), int64(3), object(3)
memory usage: 54.8+ KB

In [27]:
df

     Education  Experience  Location Job_Title  Age  Gender         Salary
0            0           8     Urban   Manager   63    Male   84620.053665
1            3          11  Suburban  Director   59    Male  142591.255894
2            1          28  Suburban   Manager   61  Female   97800.255404
3            0          29     Rural  Director   45    Male   96834.671282
4            3          25     Urban   Analyst   26  Female  132157.786175
..         ...         ...       ...       ...  ...     ...            ...
995          0           8  Suburban   Analyst   25  Female   64683.389864
996          0          24     Urban  Engineer   30  Female   74468.205020
997          2          18     Rural   Analyst   44    Male   98207.026024
998          1          27  Suburban  Director   31  Female  108544.922720
999          0          25     Urban  Director   41  Female   71077.000066

[1000 rows x 7 columns]

In [28]:
df = df.drop('Gender', axis=1)
columns_to_encode = ['Job_Title', 'Location']

In [29]:
df

     Education  Experience  Location Job_Title  Age         Salary
0            0           8     Urban   Manager   63   84620.053665
1            3          11  Suburban  Director   59  142591.255894
2            1          28  Suburban   Manager   61   97800.255404
3            0          29     Rural  Director   45   96834.671282
4            3          25     Urban   Analyst   26  132157.786175
..         ...         ...       ...       ...  ...            ...
995          0           8  Suburban   Analyst   25   64683.389864
996          0          24     Urban  Engineer   30   74468.205020
997          2          18     Rural   Analyst   44   98207.026024
998          1          27  Suburban  Director   31  108544.922720
999          0          25     Urban  Director   41   71077.000066

[1000 rows x 6 columns]

In [30]:
df = pd.get_dummies(df, columns=['Job_Title', 'Location'], drop_first=True)

In [31]:
df

,Education,Experience,Age,Salary,Job_Title_Director,Job_Title_Engineer,Job_Title_Manager,Location_Suburban,Location_Urban
0,0,8,63,84620.053665,False,False,True,False,True
1,3,11,59,142591.255894,True,False,False,True,False
2,1,28,61,97800.255404,False,False,True,True,False
3,0,29,45,96834.671282,True,False,False,False,False
4,3,25,26,132157.786175,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...
995,0,8,25,64683.389864,False,False,False,True,False
996,0,24,30,74468.205020,False,True,False,False,True
997,2,18,44,98207.026024,False,False,False,False,False
998,1,27,31,108544.922720,True,False,False,True,False
999,0,25,41,71077.000066,True,False,False,False,True

In [32]:
df = df.astype(int)

In [33]:
df

,Education,Experience,Age,Salary,Job_Title_Director,Job_Title_Engineer,Job_Title_Manager,Location_Suburban,Location_Urban
0,0,8,63,84620,0,0,1,0,1
1,3,11,59,142591,1,0,0,1,0
2,1,28,61,97800,0,0,1,1,0
3,0,29,45,96834,1,0,0,0,0
4,3,25,26,132157,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...
995,0,8,25,64683,0,0,0,1,0
996,0,24,30,74468,0,1,0,0,1
997,2,18,44,98207,0,0,0,0,0
998,1,27,31,108544,1,0,0,1,0
999,0,25,41,71077,1,0,0,0,1

In [34]:
from sklearn.model_selection import train_test_split

# 1. Separate features (inputs) and target (output)
X = df.drop('Salary', axis=1)   # Everything except salary → inputs
y = df['Salary']                # Only salary → output

# 2. Split into 80% train and 20% test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [35]:
from sklearn.linear_model import LinearRegression

# Create the model
model = LinearRegression()

# Train the model on the training data
model.fit(X_train, y_train)

LinearRegression()

In [36]:
from sklearn.metrics import mean_squared_error, r2_score

# Predict salaries on test data
y_pred = model.predict(X_test)

# Evaluate performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error (MSE):", mse)
print("R² Score:", r2)

Mean Squared Error (MSE): 106321567.42609163
R² Score: 0.8697881263911497

In [37]:
# Compare first 10 predictions with actual salaries
comparison = pd.DataFrame({
    'Predicted Salary': y_pred[:10],
    'Actual Salary': y_test.values[:10]
})

print(comparison)

   Predicted Salary  Actual Salary
0      81675.880796          86677
1      56026.632096          56036
2     110470.179724          92226
3      99372.152976         100710
4      94319.560908          91775
5      67326.229946          52282
6      95777.122588         102139
7     118017.251987         127491
8     121157.513931         117342
9     106392.057205          99647

In [38]:
X_train.columns

Index(['Education', 'Experience', 'Age', 'Job_Title_Director',
       'Job_Title_Engineer', 'Job_Title_Manager', 'Location_Suburban',
       'Location_Urban'],
      dtype='object')

In [39]:
import pandas as pd

# Creating input with the same column names
sample_input = pd.DataFrame([{
    'Education': 2,              # Master
    'Experience': 5,
    'Age': 30,
    'Job_Title_Director': 0,
    'Job_Title_Engineer': 1,
    'Job_Title_Manager': 0,
    'Location_Suburban': 1,
    'Location_Urban': 0
}])

In [40]:
predicted_salary = model.predict(sample_input)
print("Predicted Salary:", predicted_salary[0])

Predicted Salary: 97862.74096780476

In [41]:
import joblib

# Save the model
joblib.dump(model, 'salary_model.pkl')

# Load it later like this:
# model = joblib.load('salary_model.pkl')

['salary_model.pkl']

In [43]:
from google.colab import files
files.download('salary_model.pkl')